<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib\Authentication;

use MultiAuthSampleLib\ConfigurationInterface;
use CoreInterfaces\Core\Request\RequestSetterInterface;
use Core\Authentication\CoreAuth;

/**
 * Utility class for authorization and token management.
 */
class CustomAuthManager extends CoreAuth
{
    private $config;

    /**
     * Returns an instance of this class.
     */
    public function __construct(ConfigurationInterface $config)
    {
        parent::__construct();
        $this->config = $config;
    }


    /**
     * Adds authentication parameters to request.
     */
    public function apply(RequestSetterInterface $request): void
    {
        // TODO: Add your custom authentication here
        // The following properties are available to use
        //     $this->config->getAccessToken()
        //
        // i.e Add a header through:
        //     $request->addHeader('key', 'value');
    }
}
